fix how to distinguish a command and a file

diff --git a/crror b/crror
--- a/crror
+++ b/crror
@@ -18,9 +18,13 @@ self=`__readlink_f $0`
 
 d=$( cd $( dirname "$self" ); pwd )
 
-if [ -e $1 ]; then
-    $d/crror.rb $*
-else
+command -v $1
+if [ $? -eq 0 ]; then
     $* 2>&1 | $d/crror.rb
     exit ${PIPESTATUS[0]}
+elif [ -e $1 ]; then
+    $d/crror.rb $*
+else
+    echo 'Command or file is not found.'
+    exit 1
 fi
